let message = `Initializing flux capacitor...
Compiling... Please wait for the magic to happen.
Reticulating splines...
Performing quantum calculations...
Generating witty loading messages...
Optimizing for maximum awesomeness...
Deploying the intergalactic network...
Synchronizing chronometers...
Calibrating the transdimensional portal...
Downloading the internet...
Hacking the mainframe... (Just kidding... maybe)
Booting up the neural network...
Training the AI...
Caching rainbows...
Polishing the UI...
Unlocking the secrets of the universe...
Traversing the astral plane...
Summoning the ancient ones...
Deciphering cryptic messages...
Contacting the mothership...
Searching for the hidden portal...
Awakening the sleeping giants...
Breaking the fourth wall...`

let arr = message.split("\n")
console.log(arr)